algoritmo "Questão 11)"
// Autor : Kleber Alves
// Data : 15/08/2017
var
 dimaior,dimenor,resu:real

inicio
  escreva("Esse progama calculará a áera de um losango.")
  escreval
  escreva("Digite a diagonal maior do losango e pressione ENTER: ")
  leia(dimaior)
  escreva("Digite a diagonal menor do losango e pressione ENTER: ")
  leia(dimenor)
  resu:=(dimaior+dimenor)/2
  escreva("A área do losango será: ",resu,"cm²")

fimalgoritmo
