algoritmo "Exercício 04) "
// Autor : Kleber Alves
// Data : 10/08/2017
var
  nota1,nota2,media:real

inicio
  escreva("Bem vindo ao portal!")
  escreval
  escreva("Informe suas notas e descubra sua média. Digite e pressione ENTER! ")
  escreval
  escreva("Digite sua primeira nota: ")
  leia (nota1)
  escreva("Digite sua segunda nota: ")
  leia(nota2)
  media:=(nota1*2+nota2*3)/5
  escreva("Sua média é: ",media)
  escreval
  escreva("Volte sempre e bons estudos!")

fimalgoritmo
