algoritmo "Exercício 09)"
// Autor : Kleber Alves
// Data : 14/08/2017
var
  area,maior,menor,altura:real
inicio

  escreva("Digite os valores do trapézio a qual deseja calcular a área. ")
  escreval
  escreva("Digite a base maior: ")
  leia (maior)
  escreva("Digite a base menor: ")
  leia(menor)
  escreva("Digite a altura do trapézio: ")
  leia (altura)
  area:= ((maior+menor) *altura)/2
  escreva("A área desse trapézio será: ",area, "m²")
  escreval
  escreva ("Obrigado!")
  

fimalgoritmo
