algoritmo "Exercício 03"
// Autor : Kleber Alves
// Data : 08/08/2017
var
  num1,num2,res:real
inicio
  escreva("Digite dois valores a serem divididos e pressione ENTER ")
  escreval
  escreva("Lembrando que 0 nao é divisivel!")
  escreval
  escreva("Digite o primeiro numero: ")
  leia (num1)
  escreva("digite o segundo numero: ")
  leia (num2)
  res:=(num1/num2)
  escreva("O resultado da divisão é: ",res)
  escreval
  escreva("Obrigado, volte sempre!")


fimalgoritmo
