algoritmo "Questão 23"
// Autor : Kleber Alves
// Data : 24/08/2017
var
  ang1,ang2,resu,resu2:real
inicio
  escreva("Esse programa calculará  a medida do terceiro ângulo.")
  escreval
  escreva("Digite o valor do primeiro ângulo: ")
  leia (ang1)
  escreva("Digite o valor do segundo ângulo: ")
  leia(ang2)
  resu:= (ang1+ang2-180)*-1
  escreva("O valor do terceiro ângulo é de:",resu)
fimalgoritmo
