algoritmo "Exercício 08)"
// Autor : Kleber Alves
// Data : 14/08/2017
var
peso1:real
inicio
Escreval ("Bem-vindo ao portal do nutricionista!")
  escreval
  escreva("Digite o seu peso e descubra ele em gramas. pressione ENTER: ")
  leia (peso1)
  peso1:= peso1*1000
  escreva("Seu peso em gramas será: ",peso1)
  escreval
  escreva("Lembre-se de manter uma boa dieta para uma vida mais saudavel!")
  escreval
  escreva("Obrigado e volte sempre!")
fimalgoritmo
