algoritmo "Exercício 12)"
// Autor : Kleber Alves
// Data : 16/08/2017

var
  sal,salm,quantidade:real
inicio
  escreva("Esse progama calculará quantos salários mínimos você recebe.")
  escreval
  escreva("Digite o seu salário e pressione ENTER: ")
  leia (sal)
  escreva("Digite o valor do salário mínimo e pressione ENTER: ")
  leia (salm)
  quantidade:= sal/salm
  escreva("A quantidade de salários mínimos que você recebe é de: ",quantidade)


fimalgoritmo
