algoritmo "Exercício 3.4"
// Autor : Kleber Alves
// Data : 02/10/2017
var
  n,contador:inteiro
  r:real
inicio
  escreval("Esse programa gravará 10 números e mostrará a metade de cada um deles")
  para contador de 1 ate 10 faca
    escreva("Digite o" ,contador," número e pressione ENTER: ")
    leia(n)
    escreval
    r:= n/2
      escreval
      escreval (contador, "º Número digitado foi:", n, "  A sua metade é: ",r)
      escreval
  fimpara
fimalgoritmo
