algoritmo "Exercício 3.3"
// Autor : Kleber Alves
// Data : 02/10/2017
var
  n,r,contador:inteiro
inicio
  escreval("Esse programa gravará 5 números e mostrará o quadrado dele.")
  para contador de 1 ate 5 faca
  escreval
    escreva("Digite o" ,contador," número e pressione ENTER: ")
    leia(n)
    limpatela
    r:= n*n
      escreval(contador, "º Número digitado foi:", n, ". O quadrado dele é: ",r)
  fimpara
fimalgoritmo
