algoritmo "Exercício 1.2"
// Autor :Kleber Alves
// Data : 29/08/2017
//Faça um programa que leia um número e informe se a metade do número é menor que 12
var
  num,soma:real
inicio
   escreva("Esse programa informará se a metade do numero digitado é menor que 12.")
  escreval
  escreva("Digite o numero a ser dividido pela metade e pressione ENTER: ")
  leia (num)
  soma:= num/2
  se (soma < 12)entao
    escreva ("Número menor que 12!!")
  fimse
fimalgoritmo
