algoritmo "Exercício 1.4"
// Autor : Kleber Alves
// Data : 29/08/2017
var
  num,num2:real
inicio
  escreva("Esse programa informará se o primeiro numero digitado é igual ao segundo.")
  escreval
  escreva("Digite o o primeiro número e pressione ENTER: ")
  leia (num)
  escreva("Digite o segundo número e pressione ENTER: ")
  leia (num2)
  se (num=num2) entao
    escreva ("Primeiro número igual ao segundo.")
    senao
      escreva ("Números não são iguais!")
  fimse
fimalgoritmo
