algoritmo "Exercício 1.1"
// Autor :Kleber Alves
// Data : 29/08/2017
//Faça um programa que leia um número e informe se o dobro do número é maior que 35
var
  num,soma:real

inicio
  escreva("Esse programa informará se o dobro do numero digitado é maior que 35.")
  escreval
  escreva("Digite o numero a ser dobrado e pressione ENTER: ")
  leia (num)
  soma:= num*2
  se (soma > 35)entao
    escreva ("Número maior que 35!!")
  fimse

fimalgoritmo
